# Generated by Django 6.0 on 2025-12-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_application_application_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-application_date']},
        ),
        migrations.AlterModelOptions(
            name='internshipoffer',
            options={'ordering': ['-submission_date']},
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée'), ('rejected', 'Refusée'), ('closed', 'Clôturée')], default='pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('offer', 'student_email')},
        ),
    ]
