# Generated by Django 6.0 on 2025-12-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_internshipoffer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='max_applications',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée'), ('rejected', 'Refusée'), ('closed', 'Clôturée')], default='pending', max_length=20),
        ),
    ]
