# Generated by Django 6.0 on 2025-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-application_date']},
        ),
        migrations.RemoveField(
            model_name='internshipoffer',
            name='max_applications',
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de validation'), ('validated', 'Validée'), ('rejected', 'Refusée'), ('closed', 'Clôturée')], default='pending', max_length=10),
        ),
    ]
